example_output_camera:
  R:
  - [1.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0]
  - [0.0, 0.0, 1.0]
  K:
  - [200.0, 0.0, 370.0]
  - [0.0, 200.0, 800.0]
  - [0.0, 0.0, 1.0]
  resolution: [702,1600]
  rostopic: /example_output
